/*
	CRIANDO DATABASE
*/

CREATE DATABASE APPFORM;
USE APPFORM;


/*
	CRIANDO TABELA TIPO_EQUIPAMENTO
*/
CREATE TABLE TIPO_EQUIPAMENTO(
	ID INT IDENTITY PRIMARY KEY,
	TIPO VARCHAR(50)
);


/*
	POPULANDO TIPO_EQUIPAMENTO
*/
INSERT INTO TIPO_EQUIPAMENTO VALUES ('TENSÃO');
INSERT INTO TIPO_EQUIPAMENTO VALUES ('CORRENTE');
INSERT INTO TIPO_EQUIPAMENTO VALUES ('ÓLEO');


/*
	CRIANDO TABELA ALARME_CLASSIFICACAO
*/
CREATE TABLE ALARME_CLASSIFICACAO(
	ID INT IDENTITY PRIMARY KEY,
	TIPO VARCHAR(50)
);

/*
	POPULANDO ALARME_CLASSIFICACAO
*/
INSERT INTO ALARME_CLASSIFICACAO VALUES ('URGENTE');
INSERT INTO ALARME_CLASSIFICACAO VALUES ('EMERGENTE');
INSERT INTO ALARME_CLASSIFICACAO VALUES ('ORDINARIO');


/*
	CRIANDO TABELA ALARMES
*/
CREATE TABLE ALARMES(
	ID INT IDENTITY,
	DESCRICAO VARCHAR(120),
	TP_ALARME INT,
	STATUS INT CHECK (STATUS = 0 OR STATUS = 1),
	DT_CADASTRO DATE,
	DT_SAIDA DATE,
	PRIMARY KEY (ID),
	FOREIGN KEY (TP_ALARME) REFERENCES ALARME_CLASSIFICACAO(ID)
);


/*
	CRIANDO TABELA EQUIPAMENTOS
*/
CREATE TABLE EQUIPAMENTOS(
	ID INT IDENTITY,
	DESCRICAO VARCHAR(120),
	NM_SERIE INT,
	TP_EQUIPAMENTO INT,
	DT_CADASTRO DATE,
	ALARME_ID INT,
	PRIMARY KEY (ID),
	FOREIGN KEY (TP_EQUIPAMENTO) REFERENCES TIPO_EQUIPAMENTO(ID),
	FOREIGN KEY (ALARME_ID) REFERENCES ALARMES(ID)
);










